# Generated by Django 2.0.7 on 2018-08-06 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_finished', models.DateField(default=datetime.datetime.today)),
                ('date_next', models.DateField(default=datetime.datetime.today)),
                ('date_started', models.DateField(default=datetime.datetime.today)),
                ('date_created', models.DateField(default=datetime.datetime.today)),
                ('status', models.IntegerField(default=False)),
                ('name', models.CharField(default='Quest', max_length=50)),
                ('party_size', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alive', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('cls', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40000)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventures', models.ManyToManyField(to='cp.Adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Memento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Character')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Description')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Character')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Description')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('npc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('character', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cp.Character')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='notes',
            field=models.ManyToManyField(to='cp.Note'),
        ),
        migrations.AddField(
            model_name='journal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Player'),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cp.Description'),
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cp.Player'),
        ),
        migrations.AddField(
            model_name='chamber',
            name='descriptions',
            field=models.ManyToManyField(to='cp.Description'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='characters',
            field=models.ManyToManyField(to='cp.Character'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cp.Player'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Description'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='notes',
            field=models.ManyToManyField(to='cp.Note'),
        ),
    ]
