# Generated by Django 2.0.7 on 2018-07-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cls', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adventures', models.ManyToManyField(to='cp.Adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Memento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Character')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Description')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Character')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Description')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Character')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Journal')),
                ('mementos', models.ManyToManyField(to='cp.Memento')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.File')),
            ],
        ),
        migrations.AddField(
            model_name='journal',
            name='notes',
            field=models.ManyToManyField(to='cp.Note'),
        ),
        migrations.AddField(
            model_name='journal',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Player'),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Description'),
        ),
        migrations.AddField(
            model_name='character',
            name='sheets',
            field=models.ManyToManyField(to='cp.Sheet'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='characters',
            field=models.ManyToManyField(to='cp.Character'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Description'),
        ),
    ]
