# Generated by Django 2.0.7 on 2018-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0002_auto_20180715_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='text',
            field=models.CharField(max_length=40000),
        ),
    ]
