# Generated by Django 2.0.7 on 2018-07-15 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0003_auto_20180715_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='journal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cp.Journal'),
        ),
        migrations.AddField(
            model_name='room',
            name='new_field',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cp.Description'),
        ),
    ]
