# Generated by Django 2.0.7 on 2018-07-16 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0005_auto_20180715_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='new_field',
        ),
        migrations.AddField(
            model_name='adventure',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventure',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='adventure',
            name='name',
            field=models.CharField(default='Quest', max_length=50),
        ),
        migrations.AddField(
            model_name='adventure',
            name='party_size',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='character',
            name='alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='note',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 7, 16, 10, 11, 47, 472574)),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cp.Description'),
        ),
    ]
