# Generated by Django 2.0.7 on 2018-07-16 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0006_auto_20180716_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='character',
        ),
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='room',
            name='mementos',
        ),
        migrations.RemoveField(
            model_name='room',
            name='player',
        ),
        migrations.AddField(
            model_name='character',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cp.Player'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 7, 16, 15, 28, 43, 180403)),
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
