# Generated by Django 2.0.7 on 2018-07-16 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0007_auto_20180716_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 7, 16, 19, 6, 24, 900204)),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
