# Generated by Django 2.0.7 on 2018-07-17 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0009_auto_20180716_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 7, 17, 0, 3, 35, 866638)),
        ),
    ]
