# Generated by Django 2.0.7 on 2018-07-18 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0010_auto_20180717_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cp.Player')),
            ],
        ),
        migrations.AddField(
            model_name='adventure',
            name='date_next',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='adventure',
            name='notes',
            field=models.ManyToManyField(to='cp.Note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 7, 18, 13, 38, 15, 564377)),
        ),
        migrations.AddField(
            model_name='adventure',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cp.NPC'),
        ),
    ]
