# Generated by Django 2.0.7 on 2018-07-18 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0011_auto_20180718_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 7, 18, 18, 6, 3, 189299)),
        ),
    ]
