# Generated by Django 2.0.7 on 2018-07-18 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0012_auto_20180718_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='player',
        ),
        migrations.AddField(
            model_name='player',
            name='npc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='cp.Player'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 7, 18, 18, 33, 34, 916087)),
        ),
        migrations.DeleteModel(
            name='NPC',
        ),
    ]
