# Generated by Django 2.0.7 on 2018-08-02 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0013_auto_20180718_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 8, 2, 19, 31, 8, 425087)),
        ),
        migrations.AddField(
            model_name='menu',
            name='options',
            field=models.ManyToManyField(to='cp.MenuOption'),
        ),
    ]
