# Generated by Django 2.0.7 on 2018-08-02 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0014_auto_20180802_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='options',
        ),
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 8, 2, 20, 20, 49, 600726)),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuOption',
        ),
    ]
