# Generated by Django 2.0.7 on 2018-08-02 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp', '0015_auto_20180802_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2018, 8, 2, 20, 21, 30, 191495)),
        ),
    ]
